package com.minehot.palette.utils;

import com.google.common.collect.HashBasedTable;
import com.google.common.collect.Table;
import com.minehot.palette.LegacyMaterial;
import com.minehot.palette.ModernMaterial;
import org.bukkit.Material;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.regex.Pattern;

public class MaterialUtil {
    private static final Table<String, Integer, String> LEGACY = HashBasedTable.create();
    private static final Map<String, ModernMaterial> MODERN = new HashMap<>();

    static {
        /*
        File f = new File(FileUtil.WORKING_DIR_PATH, "");
        FileUtil.clean(f);
        StringBuffer buffer = new StringBuffer();
        for(Material mt : Material.values()){
            if(mt.isLegacy()) {
                EnumSet<Material> set = EnumSet.noneOf(Material.class);
                for (byte i = 0; i < Byte.MAX_VALUE; i++) {
                    Material x = CraftLegacy.fromLegacy(new MaterialData(mt, i));
                    if(set.contains(x)) continue;
                    if(mt == Material.LEGACY_AIR || !x.isAir()) {
                        buffer.append(String.format("registerLegacyMaterial(\"%s\", %d, \"%s\");\n", mt.name().substring("LEGACY_".length()), i, x.name()));
                        set.add(x);
                    }
                }
            }
        }
        FileUtil.write(f, buffer.toString());
         */
        registerLegacyMaterial("AIR", 0, "AIR");
        registerLegacyMaterial("STONE", 0, "STONE");
        registerLegacyMaterial("STONE", 1, "GRANITE");
        registerLegacyMaterial("STONE", 2, "POLISHED_GRANITE");
        registerLegacyMaterial("STONE", 3, "DIORITE");
        registerLegacyMaterial("STONE", 4, "POLISHED_DIORITE");
        registerLegacyMaterial("STONE", 5, "ANDESITE");
        registerLegacyMaterial("STONE", 6, "POLISHED_ANDESITE");
        registerLegacyMaterial("GRASS", 0, "GRASS_BLOCK");
        registerLegacyMaterial("DIRT", 0, "DIRT");
        registerLegacyMaterial("DIRT", 1, "COARSE_DIRT");
        registerLegacyMaterial("DIRT", 2, "PODZOL");
        registerLegacyMaterial("COBBLESTONE", 0, "COBBLESTONE");
        registerLegacyMaterial("WOOD", 0, "OAK_PLANKS");
        registerLegacyMaterial("WOOD", 1, "SPRUCE_PLANKS");
        registerLegacyMaterial("WOOD", 2, "BIRCH_PLANKS");
        registerLegacyMaterial("WOOD", 3, "JUNGLE_PLANKS");
        registerLegacyMaterial("WOOD", 4, "ACACIA_PLANKS");
        registerLegacyMaterial("WOOD", 5, "DARK_OAK_PLANKS");
        registerLegacyMaterial("SAPLING", 0, "OAK_SAPLING");
        registerLegacyMaterial("SAPLING", 1, "SPRUCE_SAPLING");
        registerLegacyMaterial("SAPLING", 2, "BIRCH_SAPLING");
        registerLegacyMaterial("SAPLING", 3, "JUNGLE_SAPLING");
        registerLegacyMaterial("SAPLING", 4, "ACACIA_SAPLING");
        registerLegacyMaterial("SAPLING", 5, "DARK_OAK_SAPLING");
        registerLegacyMaterial("BEDROCK", 0, "BEDROCK");
        registerLegacyMaterial("WATER", 0, "WATER");
        registerLegacyMaterial("STATIONARY_WATER", 0, "WATER");
        registerLegacyMaterial("LAVA", 0, "LAVA");
        registerLegacyMaterial("STATIONARY_LAVA", 0, "LAVA");
        registerLegacyMaterial("SAND", 0, "SAND");
        registerLegacyMaterial("SAND", 1, "RED_SAND");
        registerLegacyMaterial("GRAVEL", 0, "GRAVEL");
        registerLegacyMaterial("GOLD_ORE", 0, "GOLD_ORE");
        registerLegacyMaterial("IRON_ORE", 0, "IRON_ORE");
        registerLegacyMaterial("COAL_ORE", 0, "COAL_ORE");
        registerLegacyMaterial("LOG", 0, "OAK_LOG");
        registerLegacyMaterial("LOG", 1, "SPRUCE_LOG");
        registerLegacyMaterial("LOG", 2, "BIRCH_LOG");
        registerLegacyMaterial("LOG", 3, "JUNGLE_LOG");
        registerLegacyMaterial("LOG", 12, "OAK_WOOD");
        registerLegacyMaterial("LOG", 13, "SPRUCE_WOOD");
        registerLegacyMaterial("LOG", 14, "BIRCH_WOOD");
        registerLegacyMaterial("LOG", 15, "JUNGLE_WOOD");
        registerLegacyMaterial("LEAVES", 0, "OAK_LEAVES");
        registerLegacyMaterial("LEAVES", 1, "SPRUCE_LEAVES");
        registerLegacyMaterial("LEAVES", 2, "BIRCH_LEAVES");
        registerLegacyMaterial("LEAVES", 3, "JUNGLE_LEAVES");
        registerLegacyMaterial("SPONGE", 0, "SPONGE");
        registerLegacyMaterial("SPONGE", 1, "WET_SPONGE");
        registerLegacyMaterial("GLASS", 0, "GLASS");
        registerLegacyMaterial("LAPIS_ORE", 0, "LAPIS_ORE");
        registerLegacyMaterial("LAPIS_BLOCK", 0, "LAPIS_BLOCK");
        registerLegacyMaterial("DISPENSER", 0, "DISPENSER");
        registerLegacyMaterial("SANDSTONE", 0, "SANDSTONE");
        registerLegacyMaterial("SANDSTONE", 1, "CHISELED_SANDSTONE");
        registerLegacyMaterial("SANDSTONE", 2, "CUT_SANDSTONE");
        registerLegacyMaterial("NOTE_BLOCK", 0, "NOTE_BLOCK");
        registerLegacyMaterial("BED_BLOCK", 0, "RED_BED");
        registerLegacyMaterial("POWERED_RAIL", 0, "POWERED_RAIL");
        registerLegacyMaterial("DETECTOR_RAIL", 0, "DETECTOR_RAIL");
        registerLegacyMaterial("PISTON_STICKY_BASE", 0, "STICKY_PISTON");
        registerLegacyMaterial("WEB", 0, "COBWEB");
        registerLegacyMaterial("LONG_GRASS", 0, "DEAD_BUSH");
        registerLegacyMaterial("LONG_GRASS", 1, "GRASS");
        registerLegacyMaterial("LONG_GRASS", 2, "FERN");
        registerLegacyMaterial("DEAD_BUSH", 0, "DEAD_BUSH");
        registerLegacyMaterial("PISTON_BASE", 0, "PISTON");
        registerLegacyMaterial("PISTON_EXTENSION", 0, "PISTON_HEAD");
        registerLegacyMaterial("WOOL", 0, "WHITE_WOOL");
        registerLegacyMaterial("WOOL", 1, "ORANGE_WOOL");
        registerLegacyMaterial("WOOL", 2, "MAGENTA_WOOL");
        registerLegacyMaterial("WOOL", 3, "LIGHT_BLUE_WOOL");
        registerLegacyMaterial("WOOL", 4, "YELLOW_WOOL");
        registerLegacyMaterial("WOOL", 5, "LIME_WOOL");
        registerLegacyMaterial("WOOL", 6, "PINK_WOOL");
        registerLegacyMaterial("WOOL", 7, "GRAY_WOOL");
        registerLegacyMaterial("WOOL", 8, "LIGHT_GRAY_WOOL");
        registerLegacyMaterial("WOOL", 9, "CYAN_WOOL");
        registerLegacyMaterial("WOOL", 10, "PURPLE_WOOL");
        registerLegacyMaterial("WOOL", 11, "BLUE_WOOL");
        registerLegacyMaterial("WOOL", 12, "BROWN_WOOL");
        registerLegacyMaterial("WOOL", 13, "GREEN_WOOL");
        registerLegacyMaterial("WOOL", 14, "RED_WOOL");
        registerLegacyMaterial("WOOL", 15, "BLACK_WOOL");
        registerLegacyMaterial("PISTON_MOVING_PIECE", 0, "MOVING_PISTON");
        registerLegacyMaterial("YELLOW_FLOWER", 0, "DANDELION");
        registerLegacyMaterial("RED_ROSE", 0, "POPPY");
        registerLegacyMaterial("RED_ROSE", 1, "BLUE_ORCHID");
        registerLegacyMaterial("RED_ROSE", 2, "ALLIUM");
        registerLegacyMaterial("RED_ROSE", 3, "AZURE_BLUET");
        registerLegacyMaterial("RED_ROSE", 4, "RED_TULIP");
        registerLegacyMaterial("RED_ROSE", 5, "ORANGE_TULIP");
        registerLegacyMaterial("RED_ROSE", 6, "WHITE_TULIP");
        registerLegacyMaterial("RED_ROSE", 7, "PINK_TULIP");
        registerLegacyMaterial("RED_ROSE", 8, "OXEYE_DAISY");
        registerLegacyMaterial("BROWN_MUSHROOM", 0, "BROWN_MUSHROOM");
        registerLegacyMaterial("RED_MUSHROOM", 0, "RED_MUSHROOM");
        registerLegacyMaterial("GOLD_BLOCK", 0, "GOLD_BLOCK");
        registerLegacyMaterial("IRON_BLOCK", 0, "IRON_BLOCK");
        registerLegacyMaterial("DOUBLE_STEP", 0, "SMOOTH_STONE_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 1, "SANDSTONE_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 2, "PETRIFIED_OAK_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 3, "COBBLESTONE_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 4, "BRICK_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 5, "STONE_BRICK_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 6, "NETHER_BRICK_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 7, "QUARTZ_SLAB");
        registerLegacyMaterial("DOUBLE_STEP", 8, "SMOOTH_STONE");
        registerLegacyMaterial("DOUBLE_STEP", 9, "SMOOTH_SANDSTONE");
        registerLegacyMaterial("DOUBLE_STEP", 15, "SMOOTH_QUARTZ");
        registerLegacyMaterial("STEP", 0, "SMOOTH_STONE_SLAB");
        registerLegacyMaterial("STEP", 1, "SANDSTONE_SLAB");
        registerLegacyMaterial("STEP", 2, "PETRIFIED_OAK_SLAB");
        registerLegacyMaterial("STEP", 3, "COBBLESTONE_SLAB");
        registerLegacyMaterial("STEP", 4, "BRICK_SLAB");
        registerLegacyMaterial("STEP", 5, "STONE_BRICK_SLAB");
        registerLegacyMaterial("STEP", 6, "NETHER_BRICK_SLAB");
        registerLegacyMaterial("STEP", 7, "QUARTZ_SLAB");
        registerLegacyMaterial("BRICK", 0, "BRICKS");
        registerLegacyMaterial("TNT", 0, "TNT");
        registerLegacyMaterial("BOOKSHELF", 0, "BOOKSHELF");
        registerLegacyMaterial("MOSSY_COBBLESTONE", 0, "MOSSY_COBBLESTONE");
        registerLegacyMaterial("OBSIDIAN", 0, "OBSIDIAN");
        registerLegacyMaterial("TORCH", 0, "WALL_TORCH");
        registerLegacyMaterial("TORCH", 5, "TORCH");
        registerLegacyMaterial("FIRE", 0, "FIRE");
        registerLegacyMaterial("MOB_SPAWNER", 0, "SPAWNER");
        registerLegacyMaterial("WOOD_STAIRS", 0, "OAK_STAIRS");
        registerLegacyMaterial("CHEST", 0, "CHEST");
        registerLegacyMaterial("REDSTONE_WIRE", 0, "REDSTONE_WIRE");
        registerLegacyMaterial("DIAMOND_ORE", 0, "DIAMOND_ORE");
        registerLegacyMaterial("DIAMOND_BLOCK", 0, "DIAMOND_BLOCK");
        registerLegacyMaterial("WORKBENCH", 0, "CRAFTING_TABLE");
        registerLegacyMaterial("CROPS", 0, "WHEAT");
        registerLegacyMaterial("SOIL", 0, "FARMLAND");
        registerLegacyMaterial("FURNACE", 0, "FURNACE");
        registerLegacyMaterial("BURNING_FURNACE", 0, "FURNACE");
        registerLegacyMaterial("SIGN_POST", 0, "OAK_SIGN");
        registerLegacyMaterial("WOODEN_DOOR", 0, "OAK_DOOR");
        registerLegacyMaterial("LADDER", 0, "LADDER");
        registerLegacyMaterial("RAILS", 0, "RAIL");
        registerLegacyMaterial("COBBLESTONE_STAIRS", 0, "COBBLESTONE_STAIRS");
        registerLegacyMaterial("WALL_SIGN", 0, "OAK_WALL_SIGN");
        registerLegacyMaterial("LEVER", 0, "LEVER");
        registerLegacyMaterial("STONE_PLATE", 0, "STONE_PRESSURE_PLATE");
        registerLegacyMaterial("IRON_DOOR_BLOCK", 0, "IRON_DOOR");
        registerLegacyMaterial("WOOD_PLATE", 0, "OAK_PRESSURE_PLATE");
        registerLegacyMaterial("REDSTONE_ORE", 0, "REDSTONE_ORE");
        registerLegacyMaterial("GLOWING_REDSTONE_ORE", 0, "REDSTONE_ORE");
        registerLegacyMaterial("REDSTONE_TORCH_OFF", 0, "REDSTONE_WALL_TORCH");
        registerLegacyMaterial("REDSTONE_TORCH_OFF", 5, "REDSTONE_TORCH");
        registerLegacyMaterial("REDSTONE_TORCH_ON", 0, "REDSTONE_WALL_TORCH");
        registerLegacyMaterial("REDSTONE_TORCH_ON", 5, "REDSTONE_TORCH");
        registerLegacyMaterial("STONE_BUTTON", 0, "STONE_BUTTON");
        registerLegacyMaterial("SNOW", 0, "SNOW");
        registerLegacyMaterial("ICE", 0, "ICE");
        registerLegacyMaterial("SNOW_BLOCK", 0, "SNOW_BLOCK");
        registerLegacyMaterial("CACTUS", 0, "CACTUS");
        registerLegacyMaterial("CLAY", 0, "CLAY");
        registerLegacyMaterial("SUGAR_CANE_BLOCK", 0, "SUGAR_CANE");
        registerLegacyMaterial("JUKEBOX", 0, "JUKEBOX");
        registerLegacyMaterial("FENCE", 0, "OAK_FENCE");
        registerLegacyMaterial("PUMPKIN", 0, "CARVED_PUMPKIN");
        registerLegacyMaterial("NETHERRACK", 0, "NETHERRACK");
        registerLegacyMaterial("SOUL_SAND", 0, "SOUL_SAND");
        registerLegacyMaterial("GLOWSTONE", 0, "GLOWSTONE");
        registerLegacyMaterial("PORTAL", 0, "NETHER_PORTAL");
        registerLegacyMaterial("JACK_O_LANTERN", 0, "JACK_O_LANTERN");
        registerLegacyMaterial("CAKE_BLOCK", 0, "CAKE");
        registerLegacyMaterial("DIODE_BLOCK_OFF", 0, "REPEATER");
        registerLegacyMaterial("DIODE_BLOCK_ON", 0, "REPEATER");
        registerLegacyMaterial("STAINED_GLASS", 0, "WHITE_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 1, "ORANGE_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 2, "MAGENTA_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 3, "LIGHT_BLUE_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 4, "YELLOW_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 5, "LIME_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 6, "PINK_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 7, "GRAY_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 8, "LIGHT_GRAY_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 9, "CYAN_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 10, "PURPLE_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 11, "BLUE_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 12, "BROWN_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 13, "GREEN_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 14, "RED_STAINED_GLASS");
        registerLegacyMaterial("STAINED_GLASS", 15, "BLACK_STAINED_GLASS");
        registerLegacyMaterial("TRAP_DOOR", 0, "OAK_TRAPDOOR");
        registerLegacyMaterial("MONSTER_EGGS", 0, "INFESTED_STONE");
        registerLegacyMaterial("MONSTER_EGGS", 1, "INFESTED_COBBLESTONE");
        registerLegacyMaterial("MONSTER_EGGS", 2, "INFESTED_STONE_BRICKS");
        registerLegacyMaterial("MONSTER_EGGS", 3, "INFESTED_MOSSY_STONE_BRICKS");
        registerLegacyMaterial("MONSTER_EGGS", 4, "INFESTED_CRACKED_STONE_BRICKS");
        registerLegacyMaterial("MONSTER_EGGS", 5, "INFESTED_CHISELED_STONE_BRICKS");
        registerLegacyMaterial("SMOOTH_BRICK", 0, "STONE_BRICKS");
        registerLegacyMaterial("SMOOTH_BRICK", 1, "MOSSY_STONE_BRICKS");
        registerLegacyMaterial("SMOOTH_BRICK", 2, "CRACKED_STONE_BRICKS");
        registerLegacyMaterial("SMOOTH_BRICK", 3, "CHISELED_STONE_BRICKS");
        registerLegacyMaterial("HUGE_MUSHROOM_1", 0, "BROWN_MUSHROOM_BLOCK");
        registerLegacyMaterial("HUGE_MUSHROOM_1", 10, "MUSHROOM_STEM");
        registerLegacyMaterial("HUGE_MUSHROOM_2", 0, "RED_MUSHROOM_BLOCK");
        registerLegacyMaterial("HUGE_MUSHROOM_2", 10, "MUSHROOM_STEM");
        registerLegacyMaterial("IRON_FENCE", 0, "IRON_BARS");
        registerLegacyMaterial("THIN_GLASS", 0, "GLASS_PANE");
        registerLegacyMaterial("MELON_BLOCK", 0, "MELON");
        registerLegacyMaterial("PUMPKIN_STEM", 0, "PUMPKIN_STEM");
        registerLegacyMaterial("MELON_STEM", 0, "MELON_STEM");
        registerLegacyMaterial("VINE", 0, "VINE");
        registerLegacyMaterial("FENCE_GATE", 0, "OAK_FENCE_GATE");
        registerLegacyMaterial("BRICK_STAIRS", 0, "BRICK_STAIRS");
        registerLegacyMaterial("SMOOTH_STAIRS", 0, "STONE_BRICK_STAIRS");
        registerLegacyMaterial("MYCEL", 0, "MYCELIUM");
        registerLegacyMaterial("WATER_LILY", 0, "LILY_PAD");
        registerLegacyMaterial("NETHER_BRICK", 0, "NETHER_BRICKS");
        registerLegacyMaterial("NETHER_FENCE", 0, "NETHER_BRICK_FENCE");
        registerLegacyMaterial("NETHER_BRICK_STAIRS", 0, "NETHER_BRICK_STAIRS");
        registerLegacyMaterial("NETHER_WARTS", 0, "NETHER_WART");
        registerLegacyMaterial("ENCHANTMENT_TABLE", 0, "ENCHANTING_TABLE");
        registerLegacyMaterial("BREWING_STAND", 0, "BREWING_STAND");
        registerLegacyMaterial("CAULDRON", 0, "CAULDRON");
        registerLegacyMaterial("CAULDRON", 1, "WATER_CAULDRON");
        registerLegacyMaterial("ENDER_PORTAL", 0, "END_PORTAL");
        registerLegacyMaterial("ENDER_PORTAL_FRAME", 0, "END_PORTAL_FRAME");
        registerLegacyMaterial("ENDER_STONE", 0, "END_STONE");
        registerLegacyMaterial("DRAGON_EGG", 0, "DRAGON_EGG");
        registerLegacyMaterial("REDSTONE_LAMP_OFF", 0, "REDSTONE_LAMP");
        registerLegacyMaterial("REDSTONE_LAMP_ON", 0, "REDSTONE_LAMP");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 0, "OAK_SLAB");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 1, "SPRUCE_SLAB");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 2, "BIRCH_SLAB");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 3, "JUNGLE_SLAB");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 4, "ACACIA_SLAB");
        registerLegacyMaterial("WOOD_DOUBLE_STEP", 5, "DARK_OAK_SLAB");
        registerLegacyMaterial("WOOD_STEP", 0, "OAK_SLAB");
        registerLegacyMaterial("WOOD_STEP", 1, "SPRUCE_SLAB");
        registerLegacyMaterial("WOOD_STEP", 2, "BIRCH_SLAB");
        registerLegacyMaterial("WOOD_STEP", 3, "JUNGLE_SLAB");
        registerLegacyMaterial("WOOD_STEP", 4, "ACACIA_SLAB");
        registerLegacyMaterial("WOOD_STEP", 5, "DARK_OAK_SLAB");
        registerLegacyMaterial("COCOA", 0, "COCOA");
        registerLegacyMaterial("SANDSTONE_STAIRS", 0, "SANDSTONE_STAIRS");
        registerLegacyMaterial("EMERALD_ORE", 0, "EMERALD_ORE");
        registerLegacyMaterial("ENDER_CHEST", 0, "ENDER_CHEST");
        registerLegacyMaterial("TRIPWIRE_HOOK", 0, "TRIPWIRE_HOOK");
        registerLegacyMaterial("TRIPWIRE", 0, "TRIPWIRE");
        registerLegacyMaterial("EMERALD_BLOCK", 0, "EMERALD_BLOCK");
        registerLegacyMaterial("SPRUCE_WOOD_STAIRS", 0, "SPRUCE_STAIRS");
        registerLegacyMaterial("BIRCH_WOOD_STAIRS", 0, "BIRCH_STAIRS");
        registerLegacyMaterial("JUNGLE_WOOD_STAIRS", 0, "JUNGLE_STAIRS");
        registerLegacyMaterial("COMMAND", 0, "COMMAND_BLOCK");
        registerLegacyMaterial("BEACON", 0, "BEACON");
        registerLegacyMaterial("COBBLE_WALL", 0, "COBBLESTONE_WALL");
        registerLegacyMaterial("COBBLE_WALL", 1, "MOSSY_COBBLESTONE_WALL");
        registerLegacyMaterial("FLOWER_POT", 0, "POTTED_CACTUS");
        registerLegacyMaterial("CARROT", 0, "CARROTS");
        registerLegacyMaterial("POTATO", 0, "POTATOES");
        registerLegacyMaterial("WOOD_BUTTON", 0, "OAK_BUTTON");
        registerLegacyMaterial("ANVIL", 0, "ANVIL");
        registerLegacyMaterial("ANVIL", 4, "CHIPPED_ANVIL");
        registerLegacyMaterial("ANVIL", 8, "DAMAGED_ANVIL");
        registerLegacyMaterial("TRAPPED_CHEST", 0, "TRAPPED_CHEST");
        registerLegacyMaterial("GOLD_PLATE", 0, "LIGHT_WEIGHTED_PRESSURE_PLATE");
        registerLegacyMaterial("IRON_PLATE", 0, "HEAVY_WEIGHTED_PRESSURE_PLATE");
        registerLegacyMaterial("REDSTONE_COMPARATOR_OFF", 0, "COMPARATOR");
        registerLegacyMaterial("REDSTONE_COMPARATOR_ON", 0, "COMPARATOR");
        registerLegacyMaterial("DAYLIGHT_DETECTOR", 0, "DAYLIGHT_DETECTOR");
        registerLegacyMaterial("REDSTONE_BLOCK", 0, "REDSTONE_BLOCK");
        registerLegacyMaterial("QUARTZ_ORE", 0, "NETHER_QUARTZ_ORE");
        registerLegacyMaterial("HOPPER", 0, "HOPPER");
        registerLegacyMaterial("QUARTZ_BLOCK", 0, "QUARTZ_BLOCK");
        registerLegacyMaterial("QUARTZ_BLOCK", 1, "CHISELED_QUARTZ_BLOCK");
        registerLegacyMaterial("QUARTZ_BLOCK", 2, "QUARTZ_PILLAR");
        registerLegacyMaterial("QUARTZ_STAIRS", 0, "QUARTZ_STAIRS");
        registerLegacyMaterial("ACTIVATOR_RAIL", 0, "ACTIVATOR_RAIL");
        registerLegacyMaterial("DROPPER", 0, "DROPPER");
        registerLegacyMaterial("STAINED_CLAY", 0, "WHITE_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 1, "ORANGE_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 2, "MAGENTA_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 3, "LIGHT_BLUE_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 4, "YELLOW_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 5, "LIME_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 6, "PINK_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 7, "GRAY_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 8, "LIGHT_GRAY_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 9, "CYAN_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 10, "PURPLE_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 11, "BLUE_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 12, "BROWN_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 13, "GREEN_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 14, "RED_TERRACOTTA");
        registerLegacyMaterial("STAINED_CLAY", 15, "BLACK_TERRACOTTA");
        registerLegacyMaterial("STAINED_GLASS_PANE", 0, "WHITE_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 1, "ORANGE_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 2, "MAGENTA_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 3, "LIGHT_BLUE_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 4, "YELLOW_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 5, "LIME_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 6, "PINK_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 7, "GRAY_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 8, "LIGHT_GRAY_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 9, "CYAN_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 10, "PURPLE_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 11, "BLUE_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 12, "BROWN_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 13, "GREEN_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 14, "RED_STAINED_GLASS_PANE");
        registerLegacyMaterial("STAINED_GLASS_PANE", 15, "BLACK_STAINED_GLASS_PANE");
        registerLegacyMaterial("LEAVES_2", 0, "ACACIA_LEAVES");
        registerLegacyMaterial("LEAVES_2", 1, "DARK_OAK_LEAVES");
        registerLegacyMaterial("LOG_2", 0, "ACACIA_LOG");
        registerLegacyMaterial("LOG_2", 1, "DARK_OAK_LOG");
        registerLegacyMaterial("LOG_2", 12, "ACACIA_WOOD");
        registerLegacyMaterial("LOG_2", 13, "DARK_OAK_WOOD");
        registerLegacyMaterial("ACACIA_STAIRS", 0, "ACACIA_STAIRS");
        registerLegacyMaterial("DARK_OAK_STAIRS", 0, "DARK_OAK_STAIRS");
        registerLegacyMaterial("SLIME_BLOCK", 0, "SLIME_BLOCK");
        registerLegacyMaterial("BARRIER", 0, "BARRIER");
        registerLegacyMaterial("IRON_TRAPDOOR", 0, "IRON_TRAPDOOR");
        registerLegacyMaterial("PRISMARINE", 0, "PRISMARINE");
        registerLegacyMaterial("PRISMARINE", 1, "PRISMARINE_BRICKS");
        registerLegacyMaterial("PRISMARINE", 2, "DARK_PRISMARINE");
        registerLegacyMaterial("SEA_LANTERN", 0, "SEA_LANTERN");
        registerLegacyMaterial("HAY_BLOCK", 0, "HAY_BLOCK");
        registerLegacyMaterial("CARPET", 0, "WHITE_CARPET");
        registerLegacyMaterial("CARPET", 1, "ORANGE_CARPET");
        registerLegacyMaterial("CARPET", 2, "MAGENTA_CARPET");
        registerLegacyMaterial("CARPET", 3, "LIGHT_BLUE_CARPET");
        registerLegacyMaterial("CARPET", 4, "YELLOW_CARPET");
        registerLegacyMaterial("CARPET", 5, "LIME_CARPET");
        registerLegacyMaterial("CARPET", 6, "PINK_CARPET");
        registerLegacyMaterial("CARPET", 7, "GRAY_CARPET");
        registerLegacyMaterial("CARPET", 8, "LIGHT_GRAY_CARPET");
        registerLegacyMaterial("CARPET", 9, "CYAN_CARPET");
        registerLegacyMaterial("CARPET", 10, "PURPLE_CARPET");
        registerLegacyMaterial("CARPET", 11, "BLUE_CARPET");
        registerLegacyMaterial("CARPET", 12, "BROWN_CARPET");
        registerLegacyMaterial("CARPET", 13, "GREEN_CARPET");
        registerLegacyMaterial("CARPET", 14, "RED_CARPET");
        registerLegacyMaterial("CARPET", 15, "BLACK_CARPET");
        registerLegacyMaterial("HARD_CLAY", 0, "TERRACOTTA");
        registerLegacyMaterial("COAL_BLOCK", 0, "COAL_BLOCK");
        registerLegacyMaterial("PACKED_ICE", 0, "PACKED_ICE");
        registerLegacyMaterial("DOUBLE_PLANT", 0, "SUNFLOWER");
        registerLegacyMaterial("DOUBLE_PLANT", 1, "LILAC");
        registerLegacyMaterial("DOUBLE_PLANT", 2, "TALL_GRASS");
        registerLegacyMaterial("DOUBLE_PLANT", 3, "LARGE_FERN");
        registerLegacyMaterial("DOUBLE_PLANT", 4, "ROSE_BUSH");
        registerLegacyMaterial("DOUBLE_PLANT", 5, "PEONY");
        registerLegacyMaterial("STANDING_BANNER", 0, "WHITE_BANNER");
        registerLegacyMaterial("WALL_BANNER", 0, "WHITE_WALL_BANNER");
        registerLegacyMaterial("DAYLIGHT_DETECTOR_INVERTED", 0, "DAYLIGHT_DETECTOR");
        registerLegacyMaterial("RED_SANDSTONE", 0, "RED_SANDSTONE");
        registerLegacyMaterial("RED_SANDSTONE", 1, "CHISELED_RED_SANDSTONE");
        registerLegacyMaterial("RED_SANDSTONE", 2, "CUT_RED_SANDSTONE");
        registerLegacyMaterial("RED_SANDSTONE_STAIRS", 0, "RED_SANDSTONE_STAIRS");
        registerLegacyMaterial("DOUBLE_STONE_SLAB2", 0, "RED_SANDSTONE_SLAB");
        registerLegacyMaterial("DOUBLE_STONE_SLAB2", 8, "SMOOTH_RED_SANDSTONE");
        registerLegacyMaterial("STONE_SLAB2", 0, "RED_SANDSTONE_SLAB");
        registerLegacyMaterial("SPRUCE_FENCE_GATE", 0, "SPRUCE_FENCE_GATE");
        registerLegacyMaterial("BIRCH_FENCE_GATE", 0, "BIRCH_FENCE_GATE");
        registerLegacyMaterial("JUNGLE_FENCE_GATE", 0, "JUNGLE_FENCE_GATE");
        registerLegacyMaterial("DARK_OAK_FENCE_GATE", 0, "DARK_OAK_FENCE_GATE");
        registerLegacyMaterial("ACACIA_FENCE_GATE", 0, "ACACIA_FENCE_GATE");
        registerLegacyMaterial("SPRUCE_FENCE", 0, "SPRUCE_FENCE");
        registerLegacyMaterial("BIRCH_FENCE", 0, "BIRCH_FENCE");
        registerLegacyMaterial("JUNGLE_FENCE", 0, "JUNGLE_FENCE");
        registerLegacyMaterial("DARK_OAK_FENCE", 0, "DARK_OAK_FENCE");
        registerLegacyMaterial("ACACIA_FENCE", 0, "ACACIA_FENCE");
        registerLegacyMaterial("SPRUCE_DOOR", 0, "SPRUCE_DOOR");
        registerLegacyMaterial("BIRCH_DOOR", 0, "BIRCH_DOOR");
        registerLegacyMaterial("JUNGLE_DOOR", 0, "JUNGLE_DOOR");
        registerLegacyMaterial("ACACIA_DOOR", 0, "ACACIA_DOOR");
        registerLegacyMaterial("DARK_OAK_DOOR", 0, "DARK_OAK_DOOR");
        registerLegacyMaterial("END_ROD", 0, "END_ROD");
        registerLegacyMaterial("CHORUS_PLANT", 0, "CHORUS_PLANT");
        registerLegacyMaterial("CHORUS_FLOWER", 0, "CHORUS_FLOWER");
        registerLegacyMaterial("PURPUR_BLOCK", 0, "PURPUR_BLOCK");
        registerLegacyMaterial("PURPUR_PILLAR", 0, "PURPUR_PILLAR");
        registerLegacyMaterial("PURPUR_STAIRS", 0, "PURPUR_STAIRS");
        registerLegacyMaterial("PURPUR_DOUBLE_SLAB", 0, "PURPUR_SLAB");
        registerLegacyMaterial("PURPUR_SLAB", 0, "PURPUR_SLAB");
        registerLegacyMaterial("END_BRICKS", 0, "END_STONE_BRICKS");
        registerLegacyMaterial("BEETROOT_BLOCK", 0, "BEETROOTS");
        registerLegacyMaterial("GRASS_PATH", 0, "DIRT_PATH");
        registerLegacyMaterial("END_GATEWAY", 0, "END_GATEWAY");
        registerLegacyMaterial("COMMAND_REPEATING", 0, "REPEATING_COMMAND_BLOCK");
        registerLegacyMaterial("COMMAND_CHAIN", 0, "CHAIN_COMMAND_BLOCK");
        registerLegacyMaterial("FROSTED_ICE", 0, "FROSTED_ICE");
        registerLegacyMaterial("MAGMA", 0, "MAGMA_BLOCK");
        registerLegacyMaterial("NETHER_WART_BLOCK", 0, "NETHER_WART_BLOCK");
        registerLegacyMaterial("RED_NETHER_BRICK", 0, "RED_NETHER_BRICKS");
        registerLegacyMaterial("BONE_BLOCK", 0, "BONE_BLOCK");
        registerLegacyMaterial("STRUCTURE_VOID", 0, "STRUCTURE_VOID");
        registerLegacyMaterial("OBSERVER", 0, "OBSERVER");
        registerLegacyMaterial("WHITE_SHULKER_BOX", 0, "WHITE_SHULKER_BOX");
        registerLegacyMaterial("ORANGE_SHULKER_BOX", 0, "ORANGE_SHULKER_BOX");
        registerLegacyMaterial("MAGENTA_SHULKER_BOX", 0, "MAGENTA_SHULKER_BOX");
        registerLegacyMaterial("LIGHT_BLUE_SHULKER_BOX", 0, "LIGHT_BLUE_SHULKER_BOX");
        registerLegacyMaterial("YELLOW_SHULKER_BOX", 0, "YELLOW_SHULKER_BOX");
        registerLegacyMaterial("LIME_SHULKER_BOX", 0, "LIME_SHULKER_BOX");
        registerLegacyMaterial("PINK_SHULKER_BOX", 0, "PINK_SHULKER_BOX");
        registerLegacyMaterial("GRAY_SHULKER_BOX", 0, "GRAY_SHULKER_BOX");
        registerLegacyMaterial("SILVER_SHULKER_BOX", 0, "LIGHT_GRAY_SHULKER_BOX");
        registerLegacyMaterial("CYAN_SHULKER_BOX", 0, "CYAN_SHULKER_BOX");
        registerLegacyMaterial("PURPLE_SHULKER_BOX", 0, "SHULKER_BOX");
        registerLegacyMaterial("BLUE_SHULKER_BOX", 0, "BLUE_SHULKER_BOX");
        registerLegacyMaterial("BROWN_SHULKER_BOX", 0, "BROWN_SHULKER_BOX");
        registerLegacyMaterial("GREEN_SHULKER_BOX", 0, "GREEN_SHULKER_BOX");
        registerLegacyMaterial("RED_SHULKER_BOX", 0, "RED_SHULKER_BOX");
        registerLegacyMaterial("BLACK_SHULKER_BOX", 0, "BLACK_SHULKER_BOX");
        registerLegacyMaterial("WHITE_GLAZED_TERRACOTTA", 0, "WHITE_GLAZED_TERRACOTTA");
        registerLegacyMaterial("ORANGE_GLAZED_TERRACOTTA", 0, "ORANGE_GLAZED_TERRACOTTA");
        registerLegacyMaterial("MAGENTA_GLAZED_TERRACOTTA", 0, "MAGENTA_GLAZED_TERRACOTTA");
        registerLegacyMaterial("LIGHT_BLUE_GLAZED_TERRACOTTA", 0, "LIGHT_BLUE_GLAZED_TERRACOTTA");
        registerLegacyMaterial("YELLOW_GLAZED_TERRACOTTA", 0, "YELLOW_GLAZED_TERRACOTTA");
        registerLegacyMaterial("LIME_GLAZED_TERRACOTTA", 0, "LIME_GLAZED_TERRACOTTA");
        registerLegacyMaterial("PINK_GLAZED_TERRACOTTA", 0, "PINK_GLAZED_TERRACOTTA");
        registerLegacyMaterial("GRAY_GLAZED_TERRACOTTA", 0, "GRAY_GLAZED_TERRACOTTA");
        registerLegacyMaterial("SILVER_GLAZED_TERRACOTTA", 0, "LIGHT_GRAY_GLAZED_TERRACOTTA");
        registerLegacyMaterial("CYAN_GLAZED_TERRACOTTA", 0, "CYAN_GLAZED_TERRACOTTA");
        registerLegacyMaterial("PURPLE_GLAZED_TERRACOTTA", 0, "PURPLE_GLAZED_TERRACOTTA");
        registerLegacyMaterial("BLUE_GLAZED_TERRACOTTA", 0, "BLUE_GLAZED_TERRACOTTA");
        registerLegacyMaterial("BROWN_GLAZED_TERRACOTTA", 0, "BROWN_GLAZED_TERRACOTTA");
        registerLegacyMaterial("GREEN_GLAZED_TERRACOTTA", 0, "GREEN_GLAZED_TERRACOTTA");
        registerLegacyMaterial("RED_GLAZED_TERRACOTTA", 0, "RED_GLAZED_TERRACOTTA");
        registerLegacyMaterial("BLACK_GLAZED_TERRACOTTA", 0, "BLACK_GLAZED_TERRACOTTA");
        registerLegacyMaterial("CONCRETE", 0, "WHITE_CONCRETE");
        registerLegacyMaterial("CONCRETE", 1, "ORANGE_CONCRETE");
        registerLegacyMaterial("CONCRETE", 2, "MAGENTA_CONCRETE");
        registerLegacyMaterial("CONCRETE", 3, "LIGHT_BLUE_CONCRETE");
        registerLegacyMaterial("CONCRETE", 4, "YELLOW_CONCRETE");
        registerLegacyMaterial("CONCRETE", 5, "LIME_CONCRETE");
        registerLegacyMaterial("CONCRETE", 6, "PINK_CONCRETE");
        registerLegacyMaterial("CONCRETE", 7, "GRAY_CONCRETE");
        registerLegacyMaterial("CONCRETE", 8, "LIGHT_GRAY_CONCRETE");
        registerLegacyMaterial("CONCRETE", 9, "CYAN_CONCRETE");
        registerLegacyMaterial("CONCRETE", 10, "PURPLE_CONCRETE");
        registerLegacyMaterial("CONCRETE", 11, "BLUE_CONCRETE");
        registerLegacyMaterial("CONCRETE", 12, "BROWN_CONCRETE");
        registerLegacyMaterial("CONCRETE", 13, "GREEN_CONCRETE");
        registerLegacyMaterial("CONCRETE", 14, "RED_CONCRETE");
        registerLegacyMaterial("CONCRETE", 15, "BLACK_CONCRETE");
        registerLegacyMaterial("CONCRETE_POWDER", 0, "WHITE_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 1, "ORANGE_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 2, "MAGENTA_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 3, "LIGHT_BLUE_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 4, "YELLOW_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 5, "LIME_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 6, "PINK_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 7, "GRAY_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 8, "LIGHT_GRAY_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 9, "CYAN_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 10, "PURPLE_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 11, "BLUE_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 12, "BROWN_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 13, "GREEN_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 14, "RED_CONCRETE_POWDER");
        registerLegacyMaterial("CONCRETE_POWDER", 15, "BLACK_CONCRETE_POWDER");
        registerLegacyMaterial("STRUCTURE_BLOCK", 0, "STRUCTURE_BLOCK");
        registerLegacyMaterial("IRON_SPADE", 0, "IRON_SHOVEL");
        registerLegacyMaterial("IRON_PICKAXE", 0, "IRON_PICKAXE");
        registerLegacyMaterial("IRON_AXE", 0, "IRON_AXE");
        registerLegacyMaterial("FLINT_AND_STEEL", 0, "FLINT_AND_STEEL");
        registerLegacyMaterial("APPLE", 0, "APPLE");
        registerLegacyMaterial("BOW", 0, "BOW");
        registerLegacyMaterial("ARROW", 0, "ARROW");
        registerLegacyMaterial("COAL", 0, "COAL");
        registerLegacyMaterial("COAL", 1, "CHARCOAL");
        registerLegacyMaterial("DIAMOND", 0, "DIAMOND");
        registerLegacyMaterial("IRON_INGOT", 0, "IRON_INGOT");
        registerLegacyMaterial("GOLD_INGOT", 0, "GOLD_INGOT");
        registerLegacyMaterial("IRON_SWORD", 0, "IRON_SWORD");
        registerLegacyMaterial("WOOD_SWORD", 0, "WOODEN_SWORD");
        registerLegacyMaterial("WOOD_SPADE", 0, "WOODEN_SHOVEL");
        registerLegacyMaterial("WOOD_PICKAXE", 0, "WOODEN_PICKAXE");
        registerLegacyMaterial("WOOD_AXE", 0, "WOODEN_AXE");
        registerLegacyMaterial("STONE_SWORD", 0, "STONE_SWORD");
        registerLegacyMaterial("STONE_SPADE", 0, "STONE_SHOVEL");
        registerLegacyMaterial("STONE_PICKAXE", 0, "STONE_PICKAXE");
        registerLegacyMaterial("STONE_AXE", 0, "STONE_AXE");
        registerLegacyMaterial("DIAMOND_SWORD", 0, "DIAMOND_SWORD");
        registerLegacyMaterial("DIAMOND_SPADE", 0, "DIAMOND_SHOVEL");
        registerLegacyMaterial("DIAMOND_PICKAXE", 0, "DIAMOND_PICKAXE");
        registerLegacyMaterial("DIAMOND_AXE", 0, "DIAMOND_AXE");
        registerLegacyMaterial("STICK", 0, "STICK");
        registerLegacyMaterial("BOWL", 0, "BOWL");
        registerLegacyMaterial("MUSHROOM_SOUP", 0, "MUSHROOM_STEW");
        registerLegacyMaterial("GOLD_SWORD", 0, "GOLDEN_SWORD");
        registerLegacyMaterial("GOLD_SPADE", 0, "GOLDEN_SHOVEL");
        registerLegacyMaterial("GOLD_PICKAXE", 0, "GOLDEN_PICKAXE");
        registerLegacyMaterial("GOLD_AXE", 0, "GOLDEN_AXE");
        registerLegacyMaterial("STRING", 0, "STRING");
        registerLegacyMaterial("FEATHER", 0, "FEATHER");
        registerLegacyMaterial("SULPHUR", 0, "GUNPOWDER");
        registerLegacyMaterial("WOOD_HOE", 0, "WOODEN_HOE");
        registerLegacyMaterial("STONE_HOE", 0, "STONE_HOE");
        registerLegacyMaterial("IRON_HOE", 0, "IRON_HOE");
        registerLegacyMaterial("DIAMOND_HOE", 0, "DIAMOND_HOE");
        registerLegacyMaterial("GOLD_HOE", 0, "GOLDEN_HOE");
        registerLegacyMaterial("SEEDS", 0, "WHEAT_SEEDS");
        registerLegacyMaterial("WHEAT", 0, "WHEAT");
        registerLegacyMaterial("BREAD", 0, "BREAD");
        registerLegacyMaterial("LEATHER_HELMET", 0, "LEATHER_HELMET");
        registerLegacyMaterial("LEATHER_CHESTPLATE", 0, "LEATHER_CHESTPLATE");
        registerLegacyMaterial("LEATHER_LEGGINGS", 0, "LEATHER_LEGGINGS");
        registerLegacyMaterial("LEATHER_BOOTS", 0, "LEATHER_BOOTS");
        registerLegacyMaterial("CHAINMAIL_HELMET", 0, "CHAINMAIL_HELMET");
        registerLegacyMaterial("CHAINMAIL_CHESTPLATE", 0, "CHAINMAIL_CHESTPLATE");
        registerLegacyMaterial("CHAINMAIL_LEGGINGS", 0, "CHAINMAIL_LEGGINGS");
        registerLegacyMaterial("CHAINMAIL_BOOTS", 0, "CHAINMAIL_BOOTS");
        registerLegacyMaterial("IRON_HELMET", 0, "IRON_HELMET");
        registerLegacyMaterial("IRON_CHESTPLATE", 0, "IRON_CHESTPLATE");
        registerLegacyMaterial("IRON_LEGGINGS", 0, "IRON_LEGGINGS");
        registerLegacyMaterial("IRON_BOOTS", 0, "IRON_BOOTS");
        registerLegacyMaterial("DIAMOND_HELMET", 0, "DIAMOND_HELMET");
        registerLegacyMaterial("DIAMOND_CHESTPLATE", 0, "DIAMOND_CHESTPLATE");
        registerLegacyMaterial("DIAMOND_LEGGINGS", 0, "DIAMOND_LEGGINGS");
        registerLegacyMaterial("DIAMOND_BOOTS", 0, "DIAMOND_BOOTS");
        registerLegacyMaterial("GOLD_HELMET", 0, "GOLDEN_HELMET");
        registerLegacyMaterial("GOLD_CHESTPLATE", 0, "GOLDEN_CHESTPLATE");
        registerLegacyMaterial("GOLD_LEGGINGS", 0, "GOLDEN_LEGGINGS");
        registerLegacyMaterial("GOLD_BOOTS", 0, "GOLDEN_BOOTS");
        registerLegacyMaterial("FLINT", 0, "FLINT");
        registerLegacyMaterial("PORK", 0, "PORKCHOP");
        registerLegacyMaterial("GRILLED_PORK", 0, "COOKED_PORKCHOP");
        registerLegacyMaterial("PAINTING", 0, "PAINTING");
        registerLegacyMaterial("GOLDEN_APPLE", 0, "GOLDEN_APPLE");
        registerLegacyMaterial("GOLDEN_APPLE", 1, "ENCHANTED_GOLDEN_APPLE");
        registerLegacyMaterial("SIGN", 0, "OAK_SIGN");
        registerLegacyMaterial("WOOD_DOOR", 0, "OAK_DOOR");
        registerLegacyMaterial("BUCKET", 0, "BUCKET");
        registerLegacyMaterial("WATER_BUCKET", 0, "WATER_BUCKET");
        registerLegacyMaterial("LAVA_BUCKET", 0, "LAVA_BUCKET");
        registerLegacyMaterial("MINECART", 0, "MINECART");
        registerLegacyMaterial("SADDLE", 0, "SADDLE");
        registerLegacyMaterial("IRON_DOOR", 0, "IRON_DOOR");
        registerLegacyMaterial("REDSTONE", 0, "REDSTONE");
        registerLegacyMaterial("SNOW_BALL", 0, "SNOWBALL");
        registerLegacyMaterial("BOAT", 0, "OAK_BOAT");
        registerLegacyMaterial("LEATHER", 0, "LEATHER");
        registerLegacyMaterial("MILK_BUCKET", 0, "MILK_BUCKET");
        registerLegacyMaterial("CLAY_BRICK", 0, "BRICK");
        registerLegacyMaterial("CLAY_BALL", 0, "CLAY_BALL");
        registerLegacyMaterial("SUGAR_CANE", 0, "SUGAR_CANE");
        registerLegacyMaterial("PAPER", 0, "PAPER");
        registerLegacyMaterial("BOOK", 0, "BOOK");
        registerLegacyMaterial("SLIME_BALL", 0, "SLIME_BALL");
        registerLegacyMaterial("STORAGE_MINECART", 0, "CHEST_MINECART");
        registerLegacyMaterial("POWERED_MINECART", 0, "FURNACE_MINECART");
        registerLegacyMaterial("EGG", 0, "EGG");
        registerLegacyMaterial("COMPASS", 0, "COMPASS");
        registerLegacyMaterial("FISHING_ROD", 0, "FISHING_ROD");
        registerLegacyMaterial("WATCH", 0, "CLOCK");
        registerLegacyMaterial("GLOWSTONE_DUST", 0, "GLOWSTONE_DUST");
        registerLegacyMaterial("RAW_FISH", 0, "COD");
        registerLegacyMaterial("RAW_FISH", 1, "SALMON");
        registerLegacyMaterial("RAW_FISH", 2, "TROPICAL_FISH");
        registerLegacyMaterial("RAW_FISH", 3, "PUFFERFISH");
        registerLegacyMaterial("COOKED_FISH", 0, "COOKED_COD");
        registerLegacyMaterial("COOKED_FISH", 1, "COOKED_SALMON");
        registerLegacyMaterial("INK_SACK", 0, "INK_SAC");
        registerLegacyMaterial("INK_SACK", 1, "RED_DYE");
        registerLegacyMaterial("INK_SACK", 2, "GREEN_DYE");
        registerLegacyMaterial("INK_SACK", 3, "COCOA_BEANS");
        registerLegacyMaterial("INK_SACK", 4, "LAPIS_LAZULI");
        registerLegacyMaterial("INK_SACK", 5, "PURPLE_DYE");
        registerLegacyMaterial("INK_SACK", 6, "CYAN_DYE");
        registerLegacyMaterial("INK_SACK", 7, "LIGHT_GRAY_DYE");
        registerLegacyMaterial("INK_SACK", 8, "GRAY_DYE");
        registerLegacyMaterial("INK_SACK", 9, "PINK_DYE");
        registerLegacyMaterial("INK_SACK", 10, "LIME_DYE");
        registerLegacyMaterial("INK_SACK", 11, "YELLOW_DYE");
        registerLegacyMaterial("INK_SACK", 12, "LIGHT_BLUE_DYE");
        registerLegacyMaterial("INK_SACK", 13, "MAGENTA_DYE");
        registerLegacyMaterial("INK_SACK", 14, "ORANGE_DYE");
        registerLegacyMaterial("INK_SACK", 15, "BONE_MEAL");
        registerLegacyMaterial("BONE", 0, "BONE");
        registerLegacyMaterial("SUGAR", 0, "SUGAR");
        registerLegacyMaterial("CAKE", 0, "CAKE");
        registerLegacyMaterial("BED", 0, "RED_BED");
        registerLegacyMaterial("BED", 1, "ORANGE_BED");
        registerLegacyMaterial("BED", 2, "MAGENTA_BED");
        registerLegacyMaterial("BED", 3, "LIGHT_BLUE_BED");
        registerLegacyMaterial("BED", 4, "YELLOW_BED");
        registerLegacyMaterial("BED", 5, "LIME_BED");
        registerLegacyMaterial("BED", 6, "PINK_BED");
        registerLegacyMaterial("BED", 7, "GRAY_BED");
        registerLegacyMaterial("BED", 8, "LIGHT_GRAY_BED");
        registerLegacyMaterial("BED", 9, "CYAN_BED");
        registerLegacyMaterial("BED", 10, "PURPLE_BED");
        registerLegacyMaterial("BED", 11, "BLUE_BED");
        registerLegacyMaterial("BED", 12, "BROWN_BED");
        registerLegacyMaterial("BED", 13, "GREEN_BED");
        registerLegacyMaterial("BED", 15, "BLACK_BED");
        registerLegacyMaterial("DIODE", 0, "REPEATER");
        registerLegacyMaterial("COOKIE", 0, "COOKIE");
        registerLegacyMaterial("MAP", 0, "FILLED_MAP");
        registerLegacyMaterial("SHEARS", 0, "SHEARS");
        registerLegacyMaterial("MELON", 0, "MELON_SLICE");
        registerLegacyMaterial("PUMPKIN_SEEDS", 0, "PUMPKIN_SEEDS");
        registerLegacyMaterial("MELON_SEEDS", 0, "MELON_SEEDS");
        registerLegacyMaterial("RAW_BEEF", 0, "BEEF");
        registerLegacyMaterial("COOKED_BEEF", 0, "COOKED_BEEF");
        registerLegacyMaterial("RAW_CHICKEN", 0, "CHICKEN");
        registerLegacyMaterial("COOKED_CHICKEN", 0, "COOKED_CHICKEN");
        registerLegacyMaterial("ROTTEN_FLESH", 0, "ROTTEN_FLESH");
        registerLegacyMaterial("ENDER_PEARL", 0, "ENDER_PEARL");
        registerLegacyMaterial("BLAZE_ROD", 0, "BLAZE_ROD");
        registerLegacyMaterial("GHAST_TEAR", 0, "GHAST_TEAR");
        registerLegacyMaterial("GOLD_NUGGET", 0, "GOLD_NUGGET");
        registerLegacyMaterial("NETHER_STALK", 0, "NETHER_WART");
        registerLegacyMaterial("POTION", 0, "POTION");
        registerLegacyMaterial("GLASS_BOTTLE", 0, "GLASS_BOTTLE");
        registerLegacyMaterial("SPIDER_EYE", 0, "SPIDER_EYE");
        registerLegacyMaterial("FERMENTED_SPIDER_EYE", 0, "FERMENTED_SPIDER_EYE");
        registerLegacyMaterial("BLAZE_POWDER", 0, "BLAZE_POWDER");
        registerLegacyMaterial("MAGMA_CREAM", 0, "MAGMA_CREAM");
        registerLegacyMaterial("BREWING_STAND_ITEM", 0, "BREWING_STAND");
        registerLegacyMaterial("CAULDRON_ITEM", 0, "CAULDRON");
        registerLegacyMaterial("EYE_OF_ENDER", 0, "ENDER_EYE");
        registerLegacyMaterial("SPECKLED_MELON", 0, "GLISTERING_MELON_SLICE");
        registerLegacyMaterial("MONSTER_EGG", 0, "PIG_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 4, "ELDER_GUARDIAN_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 5, "WITHER_SKELETON_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 6, "STRAY_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 23, "HUSK_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 27, "ZOMBIE_VILLAGER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 28, "SKELETON_HORSE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 29, "ZOMBIE_HORSE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 31, "DONKEY_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 32, "MULE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 34, "EVOKER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 35, "VEX_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 36, "VINDICATOR_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 50, "CREEPER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 51, "SKELETON_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 52, "SPIDER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 54, "ZOMBIE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 55, "SLIME_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 56, "GHAST_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 57, "ZOMBIFIED_PIGLIN_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 58, "ENDERMAN_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 59, "CAVE_SPIDER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 60, "SILVERFISH_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 61, "BLAZE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 62, "MAGMA_CUBE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 65, "BAT_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 66, "WITCH_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 67, "ENDERMITE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 68, "GUARDIAN_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 69, "SHULKER_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 91, "SHEEP_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 92, "COW_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 93, "CHICKEN_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 94, "SQUID_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 95, "WOLF_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 96, "MOOSHROOM_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 98, "OCELOT_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 100, "HORSE_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 101, "RABBIT_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 102, "POLAR_BEAR_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 103, "LLAMA_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 105, "PARROT_SPAWN_EGG");
        registerLegacyMaterial("MONSTER_EGG", 120, "VILLAGER_SPAWN_EGG");
        registerLegacyMaterial("EXP_BOTTLE", 0, "EXPERIENCE_BOTTLE");
        registerLegacyMaterial("FIREBALL", 0, "FIRE_CHARGE");
        registerLegacyMaterial("BOOK_AND_QUILL", 0, "WRITABLE_BOOK");
        registerLegacyMaterial("WRITTEN_BOOK", 0, "WRITTEN_BOOK");
        registerLegacyMaterial("EMERALD", 0, "EMERALD");
        registerLegacyMaterial("ITEM_FRAME", 0, "ITEM_FRAME");
        registerLegacyMaterial("FLOWER_POT_ITEM", 0, "FLOWER_POT");
        registerLegacyMaterial("CARROT_ITEM", 0, "CARROT");
        registerLegacyMaterial("POTATO_ITEM", 0, "POTATO");
        registerLegacyMaterial("BAKED_POTATO", 0, "BAKED_POTATO");
        registerLegacyMaterial("POISONOUS_POTATO", 0, "POISONOUS_POTATO");
        registerLegacyMaterial("EMPTY_MAP", 0, "MAP");
        registerLegacyMaterial("GOLDEN_CARROT", 0, "GOLDEN_CARROT");
        registerLegacyMaterial("SKULL_ITEM", 0, "SKELETON_SKULL");
        registerLegacyMaterial("SKULL_ITEM", 1, "WITHER_SKELETON_SKULL");
        registerLegacyMaterial("SKULL_ITEM", 2, "ZOMBIE_HEAD");
        registerLegacyMaterial("SKULL_ITEM", 3, "PLAYER_HEAD");
        registerLegacyMaterial("SKULL_ITEM", 4, "CREEPER_HEAD");
        registerLegacyMaterial("SKULL_ITEM", 5, "DRAGON_HEAD");
        registerLegacyMaterial("CARROT_STICK", 0, "CARROT_ON_A_STICK");
        registerLegacyMaterial("NETHER_STAR", 0, "NETHER_STAR");
        registerLegacyMaterial("PUMPKIN_PIE", 0, "PUMPKIN_PIE");
        registerLegacyMaterial("FIREWORK", 0, "FIREWORK_ROCKET");
        registerLegacyMaterial("FIREWORK_CHARGE", 0, "FIREWORK_STAR");
        registerLegacyMaterial("ENCHANTED_BOOK", 0, "ENCHANTED_BOOK");
        registerLegacyMaterial("REDSTONE_COMPARATOR", 0, "COMPARATOR");
        registerLegacyMaterial("NETHER_BRICK_ITEM", 0, "NETHER_BRICK");
        registerLegacyMaterial("QUARTZ", 0, "QUARTZ");
        registerLegacyMaterial("EXPLOSIVE_MINECART", 0, "TNT_MINECART");
        registerLegacyMaterial("HOPPER_MINECART", 0, "HOPPER_MINECART");
        registerLegacyMaterial("PRISMARINE_SHARD", 0, "PRISMARINE_SHARD");
        registerLegacyMaterial("PRISMARINE_CRYSTALS", 0, "PRISMARINE_CRYSTALS");
        registerLegacyMaterial("RABBIT", 0, "RABBIT");
        registerLegacyMaterial("COOKED_RABBIT", 0, "COOKED_RABBIT");
        registerLegacyMaterial("RABBIT_STEW", 0, "RABBIT_STEW");
        registerLegacyMaterial("RABBIT_FOOT", 0, "RABBIT_FOOT");
        registerLegacyMaterial("RABBIT_HIDE", 0, "RABBIT_HIDE");
        registerLegacyMaterial("ARMOR_STAND", 0, "ARMOR_STAND");
        registerLegacyMaterial("IRON_BARDING", 0, "IRON_HORSE_ARMOR");
        registerLegacyMaterial("GOLD_BARDING", 0, "GOLDEN_HORSE_ARMOR");
        registerLegacyMaterial("DIAMOND_BARDING", 0, "DIAMOND_HORSE_ARMOR");
        registerLegacyMaterial("LEASH", 0, "LEAD");
        registerLegacyMaterial("NAME_TAG", 0, "NAME_TAG");
        registerLegacyMaterial("COMMAND_MINECART", 0, "COMMAND_BLOCK_MINECART");
        registerLegacyMaterial("MUTTON", 0, "MUTTON");
        registerLegacyMaterial("COOKED_MUTTON", 0, "COOKED_MUTTON");
        registerLegacyMaterial("BANNER", 0, "BLACK_BANNER");
        registerLegacyMaterial("BANNER", 1, "RED_BANNER");
        registerLegacyMaterial("BANNER", 2, "GREEN_BANNER");
        registerLegacyMaterial("BANNER", 3, "BROWN_BANNER");
        registerLegacyMaterial("BANNER", 4, "BLUE_BANNER");
        registerLegacyMaterial("BANNER", 5, "PURPLE_BANNER");
        registerLegacyMaterial("BANNER", 6, "CYAN_BANNER");
        registerLegacyMaterial("BANNER", 7, "LIGHT_GRAY_BANNER");
        registerLegacyMaterial("BANNER", 8, "GRAY_BANNER");
        registerLegacyMaterial("BANNER", 9, "PINK_BANNER");
        registerLegacyMaterial("BANNER", 10, "LIME_BANNER");
        registerLegacyMaterial("BANNER", 11, "YELLOW_BANNER");
        registerLegacyMaterial("BANNER", 12, "LIGHT_BLUE_BANNER");
        registerLegacyMaterial("BANNER", 13, "MAGENTA_BANNER");
        registerLegacyMaterial("BANNER", 14, "ORANGE_BANNER");
        registerLegacyMaterial("BANNER", 15, "WHITE_BANNER");
        registerLegacyMaterial("END_CRYSTAL", 0, "END_CRYSTAL");
        registerLegacyMaterial("SPRUCE_DOOR_ITEM", 0, "SPRUCE_DOOR");
        registerLegacyMaterial("BIRCH_DOOR_ITEM", 0, "BIRCH_DOOR");
        registerLegacyMaterial("JUNGLE_DOOR_ITEM", 0, "JUNGLE_DOOR");
        registerLegacyMaterial("ACACIA_DOOR_ITEM", 0, "ACACIA_DOOR");
        registerLegacyMaterial("DARK_OAK_DOOR_ITEM", 0, "DARK_OAK_DOOR");
        registerLegacyMaterial("CHORUS_FRUIT", 0, "CHORUS_FRUIT");
        registerLegacyMaterial("CHORUS_FRUIT_POPPED", 0, "POPPED_CHORUS_FRUIT");
        registerLegacyMaterial("BEETROOT", 0, "BEETROOT");
        registerLegacyMaterial("BEETROOT_SEEDS", 0, "BEETROOT_SEEDS");
        registerLegacyMaterial("BEETROOT_SOUP", 0, "BEETROOT_SOUP");
        registerLegacyMaterial("DRAGONS_BREATH", 0, "DRAGON_BREATH");
        registerLegacyMaterial("SPLASH_POTION", 0, "SPLASH_POTION");
        registerLegacyMaterial("SPECTRAL_ARROW", 0, "SPECTRAL_ARROW");
        registerLegacyMaterial("TIPPED_ARROW", 0, "TIPPED_ARROW");
        registerLegacyMaterial("LINGERING_POTION", 0, "LINGERING_POTION");
        registerLegacyMaterial("SHIELD", 0, "SHIELD");
        registerLegacyMaterial("ELYTRA", 0, "ELYTRA");
        registerLegacyMaterial("BOAT_SPRUCE", 0, "SPRUCE_BOAT");
        registerLegacyMaterial("BOAT_BIRCH", 0, "BIRCH_BOAT");
        registerLegacyMaterial("BOAT_JUNGLE", 0, "JUNGLE_BOAT");
        registerLegacyMaterial("BOAT_ACACIA", 0, "ACACIA_BOAT");
        registerLegacyMaterial("BOAT_DARK_OAK", 0, "DARK_OAK_BOAT");
        registerLegacyMaterial("TOTEM", 0, "TOTEM_OF_UNDYING");
        registerLegacyMaterial("SHULKER_SHELL", 0, "SHULKER_SHELL");
        registerLegacyMaterial("IRON_NUGGET", 0, "IRON_NUGGET");
        registerLegacyMaterial("KNOWLEDGE_BOOK", 0, "KNOWLEDGE_BOOK");
        registerLegacyMaterial("GOLD_RECORD", 0, "MUSIC_DISC_13");
        registerLegacyMaterial("GREEN_RECORD", 0, "MUSIC_DISC_CAT");
        registerLegacyMaterial("RECORD_3", 0, "MUSIC_DISC_BLOCKS");
        registerLegacyMaterial("RECORD_4", 0, "MUSIC_DISC_CHIRP");
        registerLegacyMaterial("RECORD_5", 0, "MUSIC_DISC_FAR");
        registerLegacyMaterial("RECORD_6", 0, "MUSIC_DISC_MALL");
        registerLegacyMaterial("RECORD_7", 0, "MUSIC_DISC_MELLOHI");
        registerLegacyMaterial("RECORD_8", 0, "MUSIC_DISC_STAL");
        registerLegacyMaterial("RECORD_9", 0, "MUSIC_DISC_STRAD");
        registerLegacyMaterial("RECORD_10", 0, "MUSIC_DISC_WARD");
        registerLegacyMaterial("RECORD_11", 0, "MUSIC_DISC_11");
        registerLegacyMaterial("RECORD_12", 0, "MUSIC_DISC_WAIT");
    }

    @Deprecated
    public static void registerLegacyMaterial(String legacy, int data, String modern){
        LEGACY.put(legacy, data, modern);
        LEGACY.put("LEGACY_" + legacy, data, modern);
        MODERN.put(modern, new ModernMaterial(legacy, data));
    }

    public static boolean isEmpty(@Nullable Material material) {
        return material == null || material == Material.AIR || material.toString().endsWith("_AIR");
    }

    @Nullable
    public static String modernize(@Nullable String material) {
        return modernize(material, 0);
    }

    @Nullable
    public static String modernize(@Nullable String material, int data) {
        if(material == null || material.isEmpty()) return null;
        material = material.toUpperCase();
        Material mt = (Material) EnumUtil.findEnum(Material.class, material);
        return mt != null ? material : LEGACY.get(material, data);
    }

    @Nullable
    public static LegacyMaterial antiquate(@Nullable String material) {
        return antiquate(material, 0);
    }

    @Nullable
    public static LegacyMaterial antiquate(@Nullable String material, int data) {
        if(material == null || material.isEmpty()) return null;
        material = material.toUpperCase();
        Material mt = (Material) EnumUtil.findEnum(Material.class, material);
        if (mt != null && mt.name().startsWith("LEGACY_")) {
            return new LegacyMaterial(mt, data);
        } else {
            ModernMaterial pair = MODERN.get(material);
            if(pair != null) {
                mt = (Material) EnumUtil.findEnum(Material.class, "LEGACY_" + pair.getMaterial());
                if (mt != null) return new LegacyMaterial(mt, pair.getVariant());
                mt = (Material) EnumUtil.findEnum(Material.class, pair.getMaterial());
                if (mt != null) return new LegacyMaterial(mt, pair.getVariant());
            }
            return null;
        }
    }

    @NotNull
    public static Optional<Material> parse(@Nullable String material) {
        return parse(material, 0);
    }

    @NotNull
    public static Optional<Material> parse(@Nullable String material, int data) {
        if(material == null || material.isEmpty()) return Optional.empty();
        material = material.toUpperCase();
        Material mt = (Material) EnumUtil.findEnum(Material.class, material);
        if(mt == null) {
            String found = LEGACY.get(material, data);
            if(found != null) {
                mt = (Material) EnumUtil.findEnum(Material.class, found);
            }
        }
        return Optional.ofNullable(mt);
    }

    @NotNull
    public static Set<Material> compileMaterialSelection(@NotNull List<String> list){
        Set<Material> set = EnumSet.noneOf(Material.class);
        for(String s : list){
            Pattern p = Pattern.compile(s.toUpperCase().replace("*", "(.*)"));
            for(Material m : Material.values()){
                if(p.matcher(m.name()).matches()) {
                    set.add(m);
                }
            }
        }
        return set;
    }
}
